# sample netlify.toml
[build]
  command = "yarn run build"
  functions = "functions" # netlify dev uses this to know where to scaffold and serve your functions
  publish = "public"

# note: each of these fields are OPTIONAL
[dev]
  command = "yarn start" # Command to start your dev server
  functions = "functions" # netlify dev uses this to know where to scaffold and serve your functions
  functionsPort = 3000
